### PR TITLE
Log whole slices in next state (another approach)

### LINKED ISSUE #19: Incorrect next state with actions updating slices of state
Imagine the following scenario:
```javascript
const state = {
  counters: {
    count1: 1,
    count2: 2,
    count3: 3
  }
};

const actions = {
  counters: {
    inc1: () => ({ count1 }) => ({ count1: count1 + 1 })
  }
};
```
Let's run `inc1()` action and here's what we see...

prev state:
```javascript
{
  count1: 1,
  count2: 2,
  count3: 3
}
```
next state:
```javascript
{ count1: 2 }
```

What's expected next state:
```javascript
{
  count1: 2,
  count2: 2,
  count3: 3
}
```

Right now logger simply returns the result of an action, and I strongly believe that it should return merged slice of a state.
[Here's an illustration](https://codepen.io/Beaglefoot/pen/JpwjmZ?editors=0010)

BTW, thanks for logger!

### PR DESCRIPTION
**Pull request by Beaglefoot**
This resolves #19 saving currently implemented interface.

One existing test was modified to correspond with new output.

### CODE REVIEW

**Comment by okwolf** [comment]
What's the purpose of adding those extra actions with underscore prefixes? I thought all we needed was to merge the current state with the action result if it would result in a state update.

Please see #24 for my approach to this problem.

**Comment by Beaglefoot** [comment]
Well, these approaches do different things:
* #23 logs the actual state which was changed as a result of an action. It takes that slice directly from state.
* #24 logs what we expect to see in state after merging the result of an action. The slice we are interested in is actually unchanged at the moment of logging.

Extra actions allow to run a sequence of actions. This is required to log slices right after each action.

```javascript
const state = {
  a: {
    b: {
      c: 'hi'
    }
  }
};

const actions = {
  a: {
    b: {
      someAction: () => ({ c: 'bye' }),
      log: () = (state, actions) => console.log(state),
      runSequence: () = (state, actions) => {
        actions.someAction();
        // state refers to state.a.b slice and will be printed
        // right after state change as a result of someAction()
        actions.log(state);
      }
    }
  }
};
```
I personally believe that #24 approach is somewhat misleading, but cannot think of a scenario where it could fail right now. It's easier to understand though.

**Comment by okwolf** [comment]
@Beaglefoot the issue you point out is one that is not unique to the logger. In general, you shouldn't refer to the old/stale state in an action after you have called another action. Instead, you should call another action that will receive the updated state.

What about #24 is misleading?

**Comment by Beaglefoot** [comment]
@okwolf By 'misleading' I mean that it actually logs out an expectation of next state not the state itself.

**Comment by okwolf** [comment]
> @Beaglefoot By 'misleading' I mean that it actually logs out an expectation of next state not the state itself.

When actions are wrapped by an HOA they are wired in to be called in between the user-provided `actions` and Hyperapp state updates. Because of when this happens the state is not updated yet, but we know exactly what data is going to be merged in that was returned by the action. Here is the Hyperapp logic that drives all of this: https://github.com/hyperapp/hyperapp/blob/62feb73302da9c02d04c16670804b472609c566f/src/index.js#L120-L128

**Comment by okwolf** [comment]
bigger better things coming soon

**Pull request closed without merging**
