### PR TITLE
Merge action result with current state to give next state value

### LINKED ISSUE #19: Incorrect next state with actions updating slices of state
Imagine the following scenario:
```javascript
const state = {
  counters: {
    count1: 1,
    count2: 2,
    count3: 3
  }
};

const actions = {
  counters: {
    inc1: () => ({ count1 }) => ({ count1: count1 + 1 })
  }
};
```
Let's run `inc1()` action and here's what we see...

prev state:
```javascript
{
  count1: 1,
  count2: 2,
  count3: 3
}
```
next state:
```javascript
{ count1: 2 }
```

What's expected next state:
```javascript
{
  count1: 2,
  count2: 2,
  count3: 3
}
```

Right now logger simply returns the result of an action, and I strongly believe that it should return merged slice of a state.
[Here's an illustration](https://codepen.io/Beaglefoot/pen/JpwjmZ?editors=0010)

BTW, thanks for logger!

### PR DESCRIPTION
**Pull request by okwolf**
Closes #19.

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@okwolf Close here? 🤔

**Review by jorgebucaran — COMMENTED** [review]
Don't know if I should approve or request changes so I am going with a comment :)

**Comment by okwolf** [comment]
@jorgebucaran I was hoping for someone to have weighed in by now if this is useful or not. 🙃

**Comment by okwolf** [comment]
bigger better things coming soon

**Pull request closed without merging**
